-- ALTER STATEMENTS

-- in were are going to discuss five different functionalities to study about ALTER statement

-----------------------------------------------------------

    -- ADD


    -- ADDING COLUMNS
ALTER TABLE ALL_TEST1 ADD (TEST_DOMAIN VARCHAR2(20)); -- ADD COLUMN

    -- ALWAYS WHEN NEW COLUMNS ARE ADDED, IT WILL BE ADDED IN THE LAST


    -- ADDING CONSTRAINTS AND ALSO GIVING NAME TO THE CONSTRAINT
ALTER TABLE ALL_TEST1 ADD CONSTRAINT TC_PK_ADDED PRIMARY KEY(TEST_CODE); -- PRIMARY KEY


    -- ADDING CHECK CONSTRAINT
ALTER TABLE TEST_TBL1 ADD CONSTRAINT TC_CHK_ADDED CHECK(TEST_SUBJ_MARK < 100);

    --ADDING NOT NULL CONSTRAINT
ALTER TABLE TEST_TBL1

